module.exports = {
    SUCCESS_RESPONSE_STATUS_CODE: 200,
    BAD_REQUEST_STATUS_CODE: 400,
    NOT_FOUND_STATUS_CODE: 404,
    METHOD_NOT_ALLOWED_STATUS_CODE: 405,
    UNPROCESSABLE_ENTITY_STATUS_CODE: 422,
    INTERVAL_SERVER_STATUS_CODE: 500,
    SUCCESS_RESPONSE_STATUS_MESSAGE: 'Successfully updated',
    BAD_REQUEST_STATUS_MESSAGE: 'Bad request',
    INTERVAL_SERVER_MESSAGE: 'Internal server error',
    NOT_FOUND_STATUS_MESSAGE: 'Not found',
    PAGE_NUMBER: '0',
    PAGE_SIZE: '10',
}